**About Book Crossing Dataset**<br>

This dataset has been compiled by Cai-Nicolas Ziegler in 2004, and it comprises of three tables for users, books and ratings. Explicit ratings are expressed on a scale from 1-10 (higher values denoting higher appreciation) and implicit rating is expressed by 0.

Reference: http://www2.informatik.uni-freiburg.de/~cziegler/BX/ 

**Objective**

This project entails building a Book Recommender System for users based on user-based and item-based collaborative filtering approaches.

#### Execute the below cell to load the datasets

In [302]:
import pandas as pd

In [303]:
#Loading data
books = pd.read_csv("books/books.csv", sep=";", error_bad_lines=False, encoding="latin-1")
books.columns = ['ISBN', 'bookTitle', 'bookAuthor', 'yearOfPublication', 'publisher', 'imageUrlS', 'imageUrlM', 'imageUrlL']

users = pd.read_csv('books/users.csv', sep=';', error_bad_lines=False, encoding="latin-1")
users.columns = ['userID', 'Location', 'Age']

ratings = pd.read_csv('books/ratings.csv', sep=';', error_bad_lines=False, encoding="latin-1")
ratings.columns = ['userID', 'ISBN', 'bookRating']

b'Skipping line 6452: expected 8 fields, saw 9\nSkipping line 43667: expected 8 fields, saw 10\nSkipping line 51751: expected 8 fields, saw 9\n'
b'Skipping line 92038: expected 8 fields, saw 9\nSkipping line 104319: expected 8 fields, saw 9\nSkipping line 121768: expected 8 fields, saw 9\n'
b'Skipping line 144058: expected 8 fields, saw 9\nSkipping line 150789: expected 8 fields, saw 9\nSkipping line 157128: expected 8 fields, saw 9\nSkipping line 180189: expected 8 fields, saw 9\nSkipping line 185738: expected 8 fields, saw 9\n'
b'Skipping line 209388: expected 8 fields, saw 9\nSkipping line 220626: expected 8 fields, saw 9\nSkipping line 227933: expected 8 fields, saw 11\nSkipping line 228957: expected 8 fields, saw 10\nSkipping line 245933: expected 8 fields, saw 9\nSkipping line 251296: expected 8 fields, saw 9\nSkipping line 259941: expected 8 fields, saw 9\nSkipping line 261529: expected 8 fields, saw 9\n'


### Check no.of records and features given in each dataset

In [304]:
books.shape # number of rows and columns respectively

(271360, 8)

In [305]:
users.shape

(278858, 3)

In [306]:
ratings.shape

(1149780, 3)

## Exploring books dataset

In [307]:
books.head()

ISBN                                          bookTitle  \
0  0195153448                                Classical Mythology   
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

             bookAuthor yearOfPublication                   publisher  \
0    Mark P. O. Morford              2002     Oxford University Press   
1  Richard Bruce Wright              2001       HarperFlamingo Canada   
2          Carlo D'Este              1991             HarperPerennial   
3      Gina Bari Kolata              1999        Farrar Straus Giroux   
4       E. J. W. Barber              1999  W. W. Norton &amp; Company   

                                           imageUrlS  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                           imageUrlM  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                           imageUrlL  
0  http://images.amazon.com/images/P/0195153448.0...  
1  http://images.amazon.com/images/P/0002005018.0...  
2  http://images.amazon.com/images/P/0060973129.0...  
3  http://images.amazon.com/images/P/0374157065.0...  
4  http://images.amazon.com/images/P/0393045218.0...

### Drop last three columns containing image URLs which will not be required for analysis

In [308]:
books.drop(books.iloc[0:0,5:], axis = 1, inplace=True)

In [309]:
books.head()

ISBN                                          bookTitle  \
0  0195153448                                Classical Mythology   
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

             bookAuthor yearOfPublication                   publisher  
0    Mark P. O. Morford              2002     Oxford University Press  
1  Richard Bruce Wright              2001       HarperFlamingo Canada  
2          Carlo D'Este              1991             HarperPerennial  
3      Gina Bari Kolata              1999        Farrar Straus Giroux  
4       E. J. W. Barber              1999  W. W. Norton &amp; Company

**yearOfPublication**

### Check unique values of yearOfPublication


In [310]:
books.yearOfPublication.unique()

array([2002, 2001, 1991, 1999, 2000, 1993, 1996, 1988, 2004, 1998, 1994,
       2003, 1997, 1983, 1979, 1995, 1982, 1985, 1992, 1986, 1978, 1980,
       1952, 1987, 1990, 1981, 1989, 1984, 0, 1968, 1961, 1958, 1974,
       1976, 1971, 1977, 1975, 1965, 1941, 1970, 1962, 1973, 1972, 1960,
       1966, 1920, 1956, 1959, 1953, 1951, 1942, 1963, 1964, 1969, 1954,
       1950, 1967, 2005, 1957, 1940, 1937, 1955, 1946, 1936, 1930, 2011,
       1925, 1948, 1943, 1947, 1945, 1923, 2020, 1939, 1926, 1938, 2030,
       1911, 1904, 1949, 1932, 1928, 1929, 1927, 1931, 1914, 2050, 1934,
       1910, 1933, 1902, 1924, 1921, 1900, 2038, 2026, 1944, 1917, 1901,
       2010, 1908, 1906, 1935, 1806, 2021, '2000', '1995', '1999', '2004',
       '2003', '1990', '1994', '1986', '1989', '2002', '1981', '1993',
       '1983', '1982', '1976', '1991', '1977', '1998', '1992', '1996',
       '0', '1997', '2001', '1974', '1968', '1987', '1984', '1988',
       '1963', '1956', '1970', '1985', '1978', '1973', '1980'

As it can be seen from above that there are some incorrect entries in this field. It looks like Publisher names 'DK Publishing Inc' and 'Gallimard' have been incorrectly loaded as yearOfPublication in dataset due to some errors in csv file.


Also some of the entries are strings and same years have been entered as numbers in some places. We will try to fix these things in the coming questions.

### Check the rows having 'DK Publishing Inc' as yearOfPublication

In [311]:
books[books['yearOfPublication'] == 'DK Publishing Inc'] # 2 rows with DK Publishing Inc as yearOfPublication

ISBN                                          bookTitle  \
209538  078946697X  DK Readers: Creating the X-Men, How It All Beg...   
221678  0789466953  DK Readers: Creating the X-Men, How Comic Book...   

       bookAuthor  yearOfPublication  \
209538       2000  DK Publishing Inc   
221678       2000  DK Publishing Inc   

                                                publisher  
209538  http://images.amazon.com/images/P/078946697X.0...  
221678  http://images.amazon.com/images/P/0789466953.0...

### Drop the rows having `'DK Publishing Inc'` and `'Gallimard'` as `yearOfPublication`

In [312]:
books[books['yearOfPublication'] == 'Gallimard'] 

ISBN                                          bookTitle  \
220731  2070426769  Peuple du ciel, suivi de 'Les Bergers\";Jean-M...   

       bookAuthor yearOfPublication  \
220731       2003         Gallimard   

                                                publisher  
220731  http://images.amazon.com/images/P/2070426769.0...

In [313]:
books.drop(books[books['yearOfPublication'] == 'DK Publishing Inc'].index, axis=0,inplace=True)
books.drop(books[books['yearOfPublication'] == 'Gallimard'].index, axis=0,inplace=True)

In [314]:
books.yearOfPublication.unique()

array([2002, 2001, 1991, 1999, 2000, 1993, 1996, 1988, 2004, 1998, 1994,
       2003, 1997, 1983, 1979, 1995, 1982, 1985, 1992, 1986, 1978, 1980,
       1952, 1987, 1990, 1981, 1989, 1984, 0, 1968, 1961, 1958, 1974,
       1976, 1971, 1977, 1975, 1965, 1941, 1970, 1962, 1973, 1972, 1960,
       1966, 1920, 1956, 1959, 1953, 1951, 1942, 1963, 1964, 1969, 1954,
       1950, 1967, 2005, 1957, 1940, 1937, 1955, 1946, 1936, 1930, 2011,
       1925, 1948, 1943, 1947, 1945, 1923, 2020, 1939, 1926, 1938, 2030,
       1911, 1904, 1949, 1932, 1928, 1929, 1927, 1931, 1914, 2050, 1934,
       1910, 1933, 1902, 1924, 1921, 1900, 2038, 2026, 1944, 1917, 1901,
       2010, 1908, 1906, 1935, 1806, 2021, '2000', '1995', '1999', '2004',
       '2003', '1990', '1994', '1986', '1989', '2002', '1981', '1993',
       '1983', '1982', '1976', '1991', '1977', '1998', '1992', '1996',
       '0', '1997', '2001', '1974', '1968', '1987', '1984', '1988',
       '1963', '1956', '1970', '1985', '1978', '1973', '1980'

### Change the datatype of yearOfPublication to 'int'

In [315]:
books['yearOfPublication'] = books['yearOfPublication'].astype('int64')

In [316]:
books.dtypes

ISBN                 object
bookTitle            object
bookAuthor           object
yearOfPublication     int64
publisher            object
dtype: object

### Drop NaNs in `'publisher'` column


In [317]:
books[books['publisher'].isna()]

ISBN        bookTitle       bookAuthor  yearOfPublication  \
128890  193169656X      Tyrant Moon  Elaine Corvidae               2002   
129037  1931696993  Finders Keepers  Linnea Sinclair               2001   

       publisher  
128890       NaN  
129037       NaN

In [318]:
books[books['bookAuthor'].isna()]

ISBN                                          bookTitle  \
187689  9627982032  The Credit Suisse Guide to Managing Your Perso...   

       bookAuthor  yearOfPublication                       publisher  
187689        NaN               1995  Edinburgh Financial Publishing

In [319]:
books.isna().sum()

ISBN                 0
bookTitle            0
bookAuthor           1
yearOfPublication    0
publisher            2
dtype: int64

In [320]:
books.drop(books[books['publisher'].isna() | books['bookAuthor'].isna()].index, axis=0, inplace=True)

In [321]:
print(books.isna().sum())#All Nan values from publisher and bookAuther removed in all 6 records removed from books df. Count 271354
print(books.shape)

ISBN                 0
bookTitle            0
bookAuthor           0
yearOfPublication    0
publisher            0
dtype: int64
(271354, 5)


## Exploring Users dataset

In [322]:
print(users.shape)
users.head()

(278858, 3)


userID                            Location   Age
0       1                  nyc, new york, usa   NaN
1       2           stockton, california, usa  18.0
2       3     moscow, yukon territory, russia   NaN
3       4           porto, v.n.gaia, portugal  17.0
4       5  farnborough, hants, united kingdom   NaN

### Get all unique values in ascending order for column `Age`

In [323]:
import numpy as np
age = pd.DataFrame(users.Age.unique())
ag = age.sort_values(by=0) 
ag

0
47     0.0
57     1.0
79     2.0
72     3.0
84     4.0
90     5.0
93     6.0
83     7.0
82     8.0
64     9.0
89    10.0
77    11.0
68    12.0
33    13.0
5     14.0
45    15.0
50    16.0
2     17.0
1     18.0
7     19.0
12    20.0
17    21.0
49    22.0
14    23.0
11    24.0
6     25.0
4     26.0
40    27.0
31    28.0
42    29.0
..     ...
157  157.0
135  159.0
120  162.0
133  168.0
115  172.0
114  175.0
150  183.0
136  186.0
164  189.0
131  199.0
140  200.0
95   201.0
151  204.0
144  207.0
155  208.0
116  209.0
129  210.0
117  212.0
110  219.0
161  220.0
153  223.0
142  226.0
149  228.0
145  229.0
87   230.0
71   231.0
118  237.0
88   239.0
101  244.0
0      NaN

[166 rows x 1 columns]

Age column has some invalid entries like nan, 0 and very high values like 100 and above

### Values below 5 and above 90 do not make much sense for our book rating case...hence replace these by NaNs

In [324]:
for i in users.Age:
    if((i < 5.0) | (i > 90.0) ):
        users.Age.replace(to_replace=i, value=np.nan, inplace = True)
        print(i)
    

0.0
1.0
103.0
104.0
231.0
3.0
119.0
2.0
93.0
4.0
114.0
230.0
239.0
148.0
151.0
101.0
201.0
96.0
123.0
244.0
133.0
91.0
128.0
94.0
141.0
110.0
97.0
219.0
124.0
92.0
175.0
172.0
209.0
212.0
237.0
162.0
100.0
156.0
136.0
95.0
106.0
99.0
108.0
210.0
199.0
147.0
168.0
132.0
159.0
186.0
152.0
102.0
116.0
200.0
115.0
226.0
137.0
207.0
229.0
138.0
109.0
105.0
228.0
183.0
204.0
98.0
223.0
113.0
208.0
107.0
157.0
111.0
146.0
118.0
220.0
143.0
140.0
189.0
127.0


In [325]:
users.Age.unique()

array([nan, 18., 17., 61., 26., 14., 25., 19., 46., 55., 32., 24., 20.,
       34., 23., 51., 31., 21., 44., 30., 57., 43., 37., 41., 54., 42.,
       50., 39., 53., 47., 36., 28., 35., 13., 58., 49., 38., 45., 62.,
       63., 27., 33., 29., 66., 40., 15., 60., 79., 22., 16., 65., 59.,
       48., 72., 56., 67., 80., 52., 69., 71., 73., 78.,  9., 64., 12.,
       74., 75., 76., 83., 68., 11., 77., 70.,  8.,  7., 81., 10.,  5.,
        6., 84., 82., 90., 85., 86., 87., 89., 88.])

### Replace null values in column `Age` with mean

In [326]:
users['Age'].fillna(users.Age.mean(), inplace= True)

In [327]:
users.Age.unique()

array([34.72384042, 18.        , 17.        , 61.        , 26.        ,
       14.        , 25.        , 19.        , 46.        , 55.        ,
       32.        , 24.        , 20.        , 34.        , 23.        ,
       51.        , 31.        , 21.        , 44.        , 30.        ,
       57.        , 43.        , 37.        , 41.        , 54.        ,
       42.        , 50.        , 39.        , 53.        , 47.        ,
       36.        , 28.        , 35.        , 13.        , 58.        ,
       49.        , 38.        , 45.        , 62.        , 63.        ,
       27.        , 33.        , 29.        , 66.        , 40.        ,
       15.        , 60.        , 79.        , 22.        , 16.        ,
       65.        , 59.        , 48.        , 72.        , 56.        ,
       67.        , 80.        , 52.        , 69.        , 71.        ,
       73.        , 78.        ,  9.        , 64.        , 12.        ,
       74.        , 75.        , 76.        , 83.        , 68.  

### Change the datatype of `Age` to `int`

In [328]:
users['Age'] = users['Age'].astype('int64')

In [329]:
print(sorted(users.Age.unique()))

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90]


## Exploring the Ratings Dataset

### check the shape

In [330]:
ratings.shape

(1149780, 3)

In [331]:
n_users = users.shape[0]
n_books = books.shape[0]

In [332]:
ratings.head(5)

userID        ISBN  bookRating
0  276725  034545104X           0
1  276726  0155061224           5
2  276727  0446520802           0
3  276729  052165615X           3
4  276729  0521795028           6

### Ratings dataset should have books only which exist in our books dataset. Drop the remaining rows

In [333]:
ratings = ratings.merge(books, left_on='ISBN', right_on='ISBN')[ratings.columns]#Merge will take only matching
#values in mentioned column ISBN and taking rest of the columns of ratings dataframe

### Ratings dataset should have ratings from users which exist in users dataset. Drop the remaining rows

In [334]:
ratings.shape

(1031129, 3)

In [335]:
ratings = ratings.merge(users, left_on='userID', right_on='userID')[ratings.columns]

In [336]:
ratings.shape # All users id match up in both the dataframes and hence change in the size

(1031129, 3)

### Consider only ratings from 1-10 and leave 0s in column `bookRating`

In [337]:
ratings['bookRating'].unique()

array([ 0,  5,  9,  8,  7,  6, 10,  3,  4,  2,  1], dtype=int64)

In [338]:
ratings = ratings[ratings['bookRating'] > 0]
ratings.shape

(383838, 3)

### Find out which rating has been given highest number of times

In [339]:
ratings['bookRating'].value_counts()# Rating  8 has the highest count

8     91803
10    71225
7     66401
9     60776
5     45355
6     31687
4      7617
3      5118
2      2375
1      1481
Name: bookRating, dtype: int64

### **Collaborative Filtering Based Recommendation Systems**

### For more accurate results only consider users who have rated atleast 100 books

In [340]:
ratcount = ratings['userID'].value_counts()
df = pd.DataFrame(ratcount) 
df = df[df['userID'] >= 100 ]
df.rename(columns={'userID' : 'count'}, inplace = True)
df['userID'] = df.index
ratings = ratings.merge(df, left_on='userID', right_on='userID')[ratings.columns]
ratings.shape # rating records reduced to 103271 with only those users with more than 100 books ratings

(103269, 3)

### Generating ratings matrix from explicit ratings


#### Note: since NaNs cannot be handled by training algorithms, replace these by 0, which indicates absence of ratings

In [341]:
ratings.isna().sum()

userID        0
ISBN          0
bookRating    0
dtype: int64

In [342]:
ratings

userID        ISBN  bookRating
0         6543  0446605484          10
1         6543  0805062971           8
2         6543  0345342968           8
3         6543  0446610038           9
4         6543  0061009059           8
5         6543  0142001740           9
6         6543  0345436911           8
7         6543  038548951X          10
8         6543  0399149562           6
9         6543  0553574566           8
10        6543  1400031354           7
11        6543  0385722206           6
12        6543  0312289723           8
13        6543  1400031346           6
14        6543  067976397X           7
15        6543  0061031550           9
16        6543  0553274503           8
17        6543  0684844826           7
18        6543  0142004278           6
19        6543  0767905385           7
20        6543  0812561864           6
21        6543  0140280553           6
22        6543  014025448X           8
23        6543  0061099015           6
24        6543  055356773X           6
25        6543  0312980140           8
26        6543  0140270590           7
27        6543  0060987103          10
28        6543  0061020710           6
29        6543  1563898586           8
...        ...         ...         ...
103239  240543  0891345957          10
103240  240543  0891347925          10
103241  240543  0891348085          10
103242  240543  0891348301          10
103243  240543  0915678004          10
103244  240543  0915678063          10
103245  240543  0915678071          10
103246  240543  0915678691          10
103247  240543  0915678705          10
103248  240543  091567887X          10
103249  240543  092926102X           7
103250  240543  0945092067          10
103251  240543  0945397216           8
103252  240543  0965833356          10
103253  240543  0967469716          10
103254  240543  1555842720           9
103255  240543  1561386170           8
103256  240543  1564582760           8
103257  240543  1564584909          10
103258  240543  1567997708          10
103259  240543  1571452249          10
103260  240543  157231947X           8
103261  240543  185172060X          10
103262  240543  1855858428          10
103263  240543  1878239295          10
103264  240543  4888720029          10
103265  240543  4888720134          10
103266  240543  4888720266          10
103267  240543  4888720304          10
103268  240543  9718728015           8

[103269 rows x 3 columns]

### Generate the predicted ratings using SVD with no.of singular values to be 50

In [343]:
R_df = ratings.pivot(index = 'userID', columns = 'ISBN', values = 'bookRating').fillna(0)

In [344]:
R_df.head()

ISBN    0000913154  0001046438  000104687X  0001047213  0001047973  \
userID                                                               
2033           0.0         0.0         0.0         0.0         0.0   
2110           0.0         0.0         0.0         0.0         0.0   
2276           0.0         0.0         0.0         0.0         0.0   
4017           0.0         0.0         0.0         0.0         0.0   
4385           0.0         0.0         0.0         0.0         0.0   

ISBN    000104799X  0001048082  0001053736  0001053744  0001055607  ...  \
userID                                                              ...   
2033           0.0         0.0         0.0         0.0         0.0  ...   
2110           0.0         0.0         0.0         0.0         0.0  ...   
2276           0.0         0.0         0.0         0.0         0.0  ...   
4017           0.0         0.0         0.0         0.0         0.0  ...   
4385           0.0         0.0         0.0         0.0         0.0  ...   

ISBN    B000092Q0A  B00009EF82  B00009NDAN  B0000DYXID  B0000T6KHI  \
userID                                                               
2033           0.0         0.0         0.0         0.0         0.0   
2110           0.0         0.0         0.0         0.0         0.0   
2276           0.0         0.0         0.0         0.0         0.0   
4017           0.0         0.0         0.0         0.0         0.0   
4385           0.0         0.0         0.0         0.0         0.0   

ISBN    B0000VZEJQ  B0000X8HIE  B00013AX9E  B0001I1KOG  B000234N3A  
userID                                                              
2033           0.0         0.0         0.0         0.0         0.0  
2110           0.0         0.0         0.0         0.0         0.0  
2276           0.0         0.0         0.0         0.0         0.0  
4017           0.0         0.0         0.0         0.0         0.0  
4385           0.0         0.0         0.0         0.0         0.0  

[5 rows x 66572 columns]

In [345]:
from scipy.sparse.linalg import svds

In [346]:
U, sigma, Vt = svds(R_df, k = 50)# Number of singular values 50 as asked

In [347]:
sigma

array([147.92121613, 149.3438051 , 150.07400599, 152.20116297,
       152.87416391, 154.61308307, 154.80093432, 155.95760177,
       158.05646578, 159.21079484, 159.81670657, 162.01963916,
       162.77851768, 163.33054635, 166.02489324, 166.8162391 ,
       168.04972004, 170.77485167, 171.01325686, 173.29428498,
       174.57624968, 176.65724713, 178.61913749, 180.29517222,
       182.25079063, 184.10706957, 187.61687534, 189.75276623,
       190.96966388, 195.14643609, 199.83133018, 201.70083339,
       202.18713912, 203.48697581, 207.26449173, 209.92986988,
       213.23598777, 216.88280493, 224.26954726, 231.66186197,
       235.67095629, 249.9581775 , 252.02866425, 261.24756904,
       267.98197504, 281.0120779 , 293.69539562, 379.58327277,
       634.72875357, 680.30978318])

In [348]:
sigma = np.diag(sigma)

In [349]:
sigma

array([[147.92121613,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        , 149.3438051 ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        , 150.07400599, ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [  0.        ,   0.        ,   0.        , ..., 379.58327277,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
        634.72875357,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        , 680.30978318]])

In [350]:
all_users_predicted_ratings = np.dot(np.dot(U, sigma), Vt)# performs the dot product

In [351]:
preds_df = pd.DataFrame(all_users_predicted_ratings, columns = R_df.columns)

In [352]:
preds_df

ISBN  0000913154  0001046438    000104687X  0001047213  0001047973  \
0       0.025341   -0.002146 -1.430820e-03   -0.002146   -0.002146   
1      -0.010012   -0.003669 -2.446297e-03   -0.003669   -0.003669   
2      -0.015054   -0.015457 -1.030440e-02   -0.015457   -0.015457   
3      -0.021499    0.035602  2.373467e-02    0.035602    0.035602   
4       0.002077   -0.007965 -5.310012e-03   -0.007965   -0.007965   
5      -0.002046    0.018614  1.240949e-02    0.018614    0.018614   
6      -0.015920    0.020221  1.348068e-02    0.020221    0.020221   
7      -0.010875   -0.010051 -6.700652e-03   -0.010051   -0.010051   
8       0.040930   -0.030352 -2.023461e-02   -0.030352   -0.030352   
9       0.023473   -0.004168 -2.778375e-03   -0.004168   -0.004168   
10     -0.005284   -0.003388 -2.258616e-03   -0.003388   -0.003388   
11      0.042806   -0.012511 -8.340806e-03   -0.012511   -0.012511   
12     -0.015425   -0.006874 -4.582765e-03   -0.006874   -0.006874   
13      0.002309    0.003484  2.322532e-03    0.003484    0.003484   
14     -0.018593   -0.000161 -1.070719e-04   -0.000161   -0.000161   
15     -0.000188   -0.000001 -8.784680e-07   -0.000001   -0.000001   
16      0.021990   -0.022691 -1.512750e-02   -0.022691   -0.022691   
17      0.000303   -0.000009 -5.779314e-06   -0.000009   -0.000009   
18      0.020472    0.000926  6.175820e-04    0.000926    0.000926   
19      0.034795   -0.008291 -5.527287e-03   -0.008291   -0.008291   
20     -0.006910   -0.001585 -1.056403e-03   -0.001585   -0.001585   
21     -0.014089    0.018299  1.219938e-02    0.018299    0.018299   
22     -0.025986    0.006893  4.595147e-03    0.006893    0.006893   
23      0.033170    0.005968  3.978462e-03    0.005968    0.005968   
24     -0.018539   -0.009831 -6.554258e-03   -0.009831   -0.009831   
25      0.027484    0.001391  9.272165e-04    0.001391    0.001391   
26      0.013153    0.019955  1.330307e-02    0.019955    0.019955   
27      0.093028   -0.035252 -2.350117e-02   -0.035252   -0.035252   
28      0.016865    0.001295  8.636081e-04    0.001295    0.001295   
29      0.037046   -0.004039 -2.692913e-03   -0.004039   -0.004039   
..           ...         ...           ...         ...         ...   
419     0.013294   -0.003049 -2.032732e-03   -0.003049   -0.003049   
420    -0.024249    0.000178  1.187523e-04    0.000178    0.000178   
421     0.022085   -0.008126 -5.417162e-03   -0.008126   -0.008126   
422    -0.000075    0.000885  5.899158e-04    0.000885    0.000885   
423    -0.028939   -0.001967 -1.311575e-03   -0.001967   -0.001967   
424    -0.005339    0.001953  1.302109e-03    0.001953    0.001953   
425    -0.023438   -0.013937 -9.291012e-03   -0.013937   -0.013937   
426     0.004881    0.033311  2.220729e-02    0.033311    0.033311   
427    -0.004095   -0.015783 -1.052181e-02   -0.015783   -0.015783   
428    -0.004114    0.004492  2.994612e-03    0.004492    0.004492   
429     0.087700   -0.004218 -2.811844e-03   -0.004218   -0.004218   
430    -0.018942    0.000377  2.516149e-04    0.000377    0.000377   
431    -0.018028   -0.010705 -7.136760e-03   -0.010705   -0.010705   
432     0.023460   -0.015269 -1.017963e-02   -0.015269   -0.015269   
433    -0.003320   -0.014015 -9.343269e-03   -0.014015   -0.014015   
434    -0.014665   -0.005670 -3.780235e-03   -0.005670   -0.005670   
435     0.004222    0.043186  2.879091e-02    0.043186    0.043186   
436     0.010294   -0.004367 -2.911182e-03   -0.004367   -0.004367   
437    -0.000455   -0.007946 -5.297431e-03   -0.007946   -0.007946   
438     0.022390    0.007448  4.965636e-03    0.007448    0.007448   
439    -0.013891   -0.008549 -5.699054e-03   -0.008549   -0.008549   
440    -0.042651   -0.007464 -4.975924e-03   -0.007464   -0.007464   
441    -0.026051   -0.030714 -2.047582e-02   -0.030714   -0.030714   
442     0.012979    0.069724  4.648285e-02    0.069724    0.069724   
443    -0.000171   -0.002851 -1.900761e-03   -0.002851   -0.002851   
444    -0.

### Take a particular user_id

### Lets find the recommendations for user with id `2110`

#### Note: Execute the below cells to get the variables loaded

In [353]:
userID = 2110

In [354]:
user_id = 2 #2nd row in ratings matrix and predicted matrix

### Get the predicted ratings for userID `2110` and sort them in descending order

In [355]:
user_row_number = user_id
sorted_user_predictions = preds_df.loc[user_row_number].sort_values(ascending = False)# sorts it in decending order

### Create a dataframe with name `user_data` containing userID `2110` explicitly interacted books

In [356]:
user_data = ratings[ratings.userID == (userID)]

In [357]:
user_data.head()

userID        ISBN  bookRating
94453    2110  059035342X          10
94454    2110  0590448595           8
94455    2110  0451137965           9
94456    2110  0590629786          10
94457    2110  0590629794          10

In [358]:
user_data.shape

(103, 3)

### Combine the user_data and and corresponding book data(`book_data`) in a single dataframe with name `user_full_info`

In [359]:
user_full_info = (user_data.merge(books, how = 'left', left_on = 'ISBN', right_on = 'ISBN').
sort_values(['bookRating'], ascending = False))
print('User {0} has already rated {1} books.'.format(userID, user_full_info.dropna().shape[0]))

User 2110 has already rated 103 books.


In [360]:
user_full_info.head()

userID        ISBN  bookRating  \
0     2110  059035342X          10   
23    2110  0140022651          10   
26    2110  0345283554          10   
27    2110  0345283929          10   
28    2110  034528710X          10   

                                            bookTitle     bookAuthor  \
0   Harry Potter and the Sorcerer's Stone (Harry P...  J. K. Rowling   
23                 Journey to the Center of the Earth    Jules Verne   
26                             Han Solo at Stars' End          Daley   
27                           Empire Strikes Back Wars  Donald F Glut   
28                       Han Solo and the Lost Legacy    Brian Daley   

    yearOfPublication               publisher  
0                1999  Arthur A. Levine Books  
23               1965           Penguin Books  
26               1979               Not Avail  
27               1980        Ballantine Books  
28               1980           Del Rey Books

### Get top 10 recommendations for above given userID from the books not already rated by that user

In [361]:
predictions = (books[~books['ISBN'].isin(user_full_info['ISBN'])].
                      merge(pd.DataFrame(sorted_user_predictions).reset_index(), how = 'left',
                           left_on = 'ISBN',
                           right_on = 'ISBN').
                      rename(columns = {user_row_number: 'Predictions'}).
                      sort_values('Predictions', ascending = False).
                      iloc[:10, :-1]) # picking only 10 records
predictions # Top 10 recommendations for the requested user

ISBN                                          bookTitle  \
407    0316666343                          The Lovely Bones: A Novel   
2116   0345350499                                The Mists of Avalon   
2438   0440214041                                  The Pelican Brief   
455    044021145X                                           The Firm   
521    0312195516                The Red Tent (Bestselling Backlist)   
20670  0345318862      Golem in the Gears (Xanth Novels (Paperback))   
4810   0345313151  Bearing an Hourglass (Incarnations of Immortal...   
6320   0380752891           Man from Mundania (Xanth Trilogy, No 12)   
44448  051511605X                                    Undue Influence   
8977   043936213X     Harry Potter and the Sorcerer's Stone (Book 1)   

                  bookAuthor  yearOfPublication                      publisher  
407             Alice Sebold               2002                  Little, Brown  
2116   MARION ZIMMER BRADLEY               1987                        Del Rey  
2438            John Grisham               1993                           Dell  
455             John Grisham               1992   Bantam Dell Publishing Group  
521            Anita Diamant               1998                    Picador USA  
20670          PIERS ANTHONY               1986                        Del Rey  
4810           Piers Anthony               1991                  Del Rey Books  
6320           Piers Anthony               1990  Harper Mass Market Paperbacks  
44448    Steven Paul Martini               1995                     Jove Books  
8977           J. K. Rowling               2001                     Scholastic

In [362]:
sorted_user_predictions

ISBN
0316666343    1.015397
059035342X    0.778665
0345350499    0.697309
0440214041    0.665439
044021145X    0.663549
0312195516    0.642840
0345318862    0.639465
0345313151    0.631446
0380752891    0.629143
051511605X    0.617955
043936213X    0.614288
0385504209    0.613232
0312966970    0.605433
0440213525    0.603722
0812548051    0.602907
0380752859    0.598778
0345322231    0.588352
0345318854    0.579409
0452282152    0.572168
0812548094    0.571572
0812517725    0.564544
0345322215    0.560832
0440211727    0.560544
0380759489    0.559758
0812551478    0.558102
006016848X    0.550815
0345313097    0.547583
0886774802    0.544630
0553280368    0.541396
0446310786    0.540219
                ...   
055321313X   -0.128899
0140251367   -0.131740
0836220854   -0.132223
0670835382   -0.133568
0375706062   -0.134258
0440404193   -0.134705
0679767789   -0.135518
0062501860   -0.135882
0140501800   -0.136724
0515090166   -0.137002
0140328696   -0.137862
0515095826   -0.138192
052594